import "./globals.css";

export const metadata = {
  title: "Gestore Documenti",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="it">
      <body className="bg-white dark:bg-slate-900 dark:text-slate-100">{children}</body>
    </html>
  );
}
